feat: late initialization of astroport oracle contract #NTRN-429
neutron-org/neutron-tge-contracts pull request #25
Opened 2023-04-04 07:49 UTC by foxpy

2023-04-04 17:16 UTC, sotnikov-s approved these changes
the rest lgtm

2023-04-05 09:32 UTC, sotnikov-s approved these changes

2023-04-06 08:42 UTC, sotnikov-s requested changes
discussed a couple of things with @foxpy and @ratik that need to be addressed:
1. remove asset_info from init msg because it will always be None in our case;
2. come to a conclusion with @ratik re amount of times the asset_info can be set during the contract's life

thus I renounce the approval

2023-04-07 08:41 UTC, sotnikov-s approved these changes

2023-04-07 09:16 UTC, oopcode approved these changes

2023-04-07 09:18 UTC, merged