twap at height NTRN-357
neutron-org/neutron-tge-contracts pull request #7
Opened 2023-02-13 15:54 UTC by quasisamurai

[TASK](https://p2pvalidator.atlassian.net/browse/NTRN-357)

This is a patched `astroport oracle` contract with necessary `astroport contracts` and also some modifications 4 Neutron needs:

- Implemented twap_at_height query
- `PERIOD` const is now parameter
- implemented simple and complex tests 

since the astroport contract has nothing to integrate with at the moment, the tests are implemented directly in the repository (see integration.rs ) discussed w @swelf19 

How to test: you don't need to since you're seeing green check mark in this PR

2023-02-17 10:16 UTC, pr0n00gler requested changes

2023-02-17 10:16 UTC, pr0n00gler commented on contracts/astroport/oracle/src/contract.rs
> +/// * **height** amount of tokens we multiply the TWAP by.
Wrong comment

2023-02-17 10:16 UTC, pr0n00gler commented on contracts/astroport/oracle/src/state.rs
> +    SnapshotItem::new("price_last", "", "", Strategy::EveryBlock);
```suggestion
    SnapshotItem::new("price_last", "price_last_checkpoints", "price_last_changelog", Strategy::EveryBlock);
```

2023-02-28 14:21 UTC, pr0n00gler approved these changes

2023-03-01 16:06 UTC, pr0n00gler approved these changes

2023-03-03 09:33 UTC, foxpy approved these changes
code looks fine, though I am not sure how are we going to resolve dependency hell with cosmwasm-std and cw-X libraries.

2023-03-03 13:10 UTC, pr0n00gler approved these changes

2023-03-03 21:47 UTC, oldremez reviewed
I believe there's a lack of tests with a height between two snapshots. Current tests cover only cases with exactly those blocks at which the oracle was updated. But in a real situation, the queries will be done to the arbitrary block that in general lies between snapshots. And what is the expected behavior here: do we need to return the past TWAP calculated or the next one (since the block we get a query for lies in the period of time for which the next TWAP is calculated, right?).

Also, out of scope but maybe we should have a todo for it: if we keep the history anyway, shouldn't we allow updating at arbitrary blocks? I mean for any block we can find the previous snapshot that is more than the `update period` far away. Or it will lead to more gas consumption?

2023-03-06 12:00 UTC, quasisamurai commented
plz don't merge this pr until this comment is removed

2023-03-07 13:16 UTC, oldremez approved these changes

2023-03-09 10:05 UTC, merged